### ISSUE TITLE
Question: Type not found: FlxKeyboard

### ISSUE THREAD

**Issue by kkkddds** [nebulazorua/vsomega#2]
I type:
class SecretShit extends FlxKeyboard
{}
in SecretShit.hx
When I run lime test windows
Cmd say: Type not found: FlxKeyboard
![image](https://user-images.githubusercontent.com/87193047/125091607-25303580-e103-11eb-9449-ec3acd3b5e3d.png)

**Comment by nebulazorua** [comment]
oh right oops shit i forgot to add the import flxkeyboard line
at the top add

`import flixel.input.keyboard.FlxKeyboard`

**Comment by kkkddds** [comment]
Thank you 👍
