### ISSUE TITLE
Enhancement: 

### ISSUE THREAD

**Issue by NebulaStellaNova** [nebulazorua/vsomega#7]
For those trying to compile the game after you add 
"import flixel.input.keyboard.FlxKeyboard
class SecretShit extends FlxKeyboard
{}"
 in SecretShit.hx it will still complain to fix add this instead:
"import flixel.input.keyboard.FlxKeyboard;
class SecretShit extends FlxKeyboard
{}"

**Comment by nebulazorua** [comment]
oh right i forgot the semicolon
